### ISSUE TITLE
How to apply the ensemble of multiple models?

### ISSUE THREAD

**Issue by dyhBUPT** [megvii-research/MOTRv2#1]
Hi, thanks for your great work with simple idea but excellent performance!

I want to ask that how do you use an ensemble of 4 models? 
You mean, 4 tracking models? or 4 detection models?

I'd appreciate it if you can show more details.

**Comment by zyayoung** [comment]
We use 4 MOTR tracking models and choose the best on sequence level.

**Comment by dyhBUPT** [comment]
> We use 4 MOTR tracking models and choose the best on sequence level.

Thanks for your reply~
