### ISSUE TITLE
user_checkpoint和CheckpointFunction的作用是什么？

### ISSUE THREAD

**Issue by chzhan** [megvii-research/MOTRv2#11]
如题，调试了一遍代码，没看懂他们的作用，为什么不计算梯度，又为什么重写backward，求解。

**Comment by zyayoung** [comment]
节约显存，为了能在2080ti上训练。

To save GPU memory and train on 2080ti.
Reference: https://pytorch.org/docs/stable/checkpoint.html

**Comment by chzhan** [comment]
非常感谢！
