### ISSUE TITLE
num_classes设置

### ISSUE THREAD

**Issue by hahapt** [megvii-research/MOTRv2#14]
加载pretrain模型r50_deformable_detr_plus_iterative_bbox_refinement-checkpoint.pth时会出现报错：
No param refine_embed.weight.If you see this, your model does not fully load the pre-trained weight. Please make sure you set the correct --num_classes for your own dataset.

请问在哪里更改num_classes设置？

**Comment by zyayoung** [comment]
不需要修改，忽略这条报错即可。
