### ISSUE TITLE
score threshold and update_score_threshold

### ISSUE THREAD

**Issue by hahapt** [megvii-research/MOTRv2#15]
I found the score threshold and update_score_threshold is set to 0.5 in submit_dance.py, then the detections under 0.5 confidence will directly be removed.  
So why it set to be 0.5?
Is there any hyper-parameter during training influence them?

**Comment by zyayoung** [comment]
We did a grid search on the score threshold and update_score_threshold during inference.

A corresponding threshold in training is also set to 0.5.
https://github.com/megvii-research/MOTRv2/blob/be49b7336218e470c9ebcd34be54fe7eec702675/models/qim.py#L70
