### ISSUE TITLE
您好，我无法在12g显存的2080ti上训练，只能在v100或3090上训练

### ISSUE THREAD

**Issue by hanzifan** [megvii-research/MOTRv2#22]
问题如题目
<img width="483" alt="微信图片_20230116214937" src="https://user-images.githubusercontent.com/43206681/212693403-8389cac7-54e3-4efd-ae61-4ab87b565f61.png">

**Comment by hanzifan** [comment]
![Uploading 微信图片_20230116215027.png…]()

**Comment by hanzifan** [comment]
<img width="789" alt="微信图片_20230116215027" src="https://user-images.githubusercontent.com/43206681/212693823-8efcc6dd-16c1-440b-95a1-7243b87cd54b.png">

**Comment by zyayoung** [comment]
从log上看，在ddp初始化阶段就出错了，可能不是显存不够的问题？
这组卡其他ddp代码是可以跑的吗？

**Comment by hanzifan** [comment]
> 
其他的ddp可以跑，可能是显存不够。我在v100上使用checkpoint运行，显存占用达到了16g。但我这个2080ti卡只有12g显存。
