### ISSUE TITLE
det_db_motrv2.json

### ISSUE THREAD

**Issue by wh1sperC** [megvii-research/MOTRv2#27]
你好，我想问一下你这个项目里面要用的det_db_motrv2.json是怎么生成的？我在这里期待你的回复，谢谢。

**Comment by 158627746** [comment]
Dataset preparation
Download YOLOX detection from [here]
点击进去以后可以下载，生成应该是用bytetrack里面的推断生成的。https://github.com/zyayoung/ByteTrackInference

**Comment by wh1sperC** [comment]
> 
我试过链接里面的那个，生成的只有DanceTrack数据集的信息，没有CrowdHuman的，怎么把CrowdHuman也加进去？

**Comment by zyayoung** [comment]
分开生成，最后把json里的dict合并一下就可以了

**Comment by yaoshanliang** [comment]
针对没有检测到的目标，det_db_motrv2.json并未包含该条信息，导致后续训练报错？
