### ISSUE TITLE
det_ db_ Is motrv2.json

### ISSUE THREAD

**Issue by l-dawei** [megvii-research/MOTRv2#3]
Hello, thanks for your great work! Excuse me,the result of det_ db_ Is motrv2.json obtained by using YOLOX? In addition, is there no code for this part in this project? I'd appreciate it if you can show more details.

**Comment by zyayoung** [comment]
Yes, det_db is obtained by YOLOX provided by ByteTrack.
You may find a sample code for inference at https://github.com/zyayoung/ByteTrackInference.

**Comment by l-dawei** [comment]
> Yes, det_db is obtained by YOLOX provided by ByteTrack. You may find a sample code for inference at https://github.com/zyayoung/ByteTrackInference.

Thanks  a lot.

**Comment by l-dawei** [comment]
> Yes, det_db is obtained by YOLOX provided by ByteTrack. You may find a sample code for inference at https://github.com/zyayoung/ByteTrackInference.

Thanks a lot. And is the function of mixed data set only to enhance the robustness of the model? Looking forward to your reply.

**Comment by zyayoung** [comment]
Mixing datasets improves performance. You may refer to our paper for performance comparison.
