### ISSUE TITLE
这个好落地吗？

### ISSUE THREAD

**Issue by David-19940718** [megvii-research/MOTRv2#4]

**Comment by hcongcong** [comment]
论文第八页“Another limitation is the computational overhead introduced by the YOLOX detector, which may hinder our MOTRv2 for the deployment on edge devices.”

**Comment by zyayoung** [comment]
落地需要部署YOLOX+MOTR

**Comment by vaesl** [comment]
服务器层面的落地应该是可以的，边缘设备落地有些困难，我们也还在推动

**Comment by vaesl** [comment]
Some update:  the MOTRv2 model can be converted to tensorrt. In our practice, it can run at 14ms with int8 bit. In the future, we may release the tensorrt version of it.

**Comment by wh1sperC** [comment]
> 落地需要部署YOLOX+MOTR

是需要先部署YOLOX+MOTR才能使用MOTRv2吗？如果要的话该怎么部署呢？
